apiVersion: v1
kind: Service
metadata:
  name: learner-report-backend-service
spec:
  selector:
    app: learner-report-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
