apiVersion: v1
kind: Service
metadata:
  name: learner-report-frontend-service
spec:
  selector:
    app: learner-report-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
