apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-service
spec:
  selector:
    app: {{ .Chart.Name }}-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
